# Generated by Django 4.1 on 2022-09-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='captions',
            new_name='caption',
        ),
    ]
